travis:
  secure:
    BINSTAR_TOKEN: 0/IS7JwkgUY0CE7wyzOoVvXNOxEWSrru2Av0NEIXOCkL005wTuxz0zM8Xmq3A3385M3U5vRJmBnWVwBGoEvb6+8KtdxhNX0erhb+0qAxpsPLd1Diefiu5W+3MDbRNHOrKtp5FmICXFSKby3XOMJm/D+z448nTMq03OfQzZOiYsKEnxD9m97agfIJFsfN2ZlEqdr/TtjYhwwdvIft4kwFZv4Cvucg/8uU2od9jmXN9AhU292Q86XQfwBf3DUYnEUeTLkqnXPjtlmWct1TNPdeqxaXC7GCEMtFyFi5bQmc8iPzkLwBkndGAqDnELqkjaF/DQEJLZQ+u6l9ncDjOK6lx22C3hzgMzwZW1624MfwS7gKvVAyqRHjFT3Ohenb06eByXb0f0wQthrD05Jn8QAKUkSfwL7Qbql0WifD84fktJlyQCEDFn/YyWZAygER5D5CSLhJJv/ngtLATtKCd7ILBCvMVao1vHkGovT0OB66Ic5fazzVzxoehcTfdJOBxRHjtIo/FLWTkBy/dUAWl9qBFQm4ORQbpQ+WoYdX/kd+lhuJQNMS0NqJ2Z0dhl9IlQZA0qJnNfjNvVMVH8phsd7WO0PvNz669Wyi62EvsSiniY2Zf0kJdrDeJx7PRpR8e+sxqlR+VhP1hD4JhowOWLt9mowqYSijXGNWba1xasYsErs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
